<map version="1.0.1">
<node TEXT="my title">
<node TEXT="Introduction {#introduction}">
<node TEXT="What is 'bookdown' {#what_is__bookdown_}"></node>
<node TEXT="What is 'bookdownplus' {#what_is__bookdownplus_}"></node>
<node TEXT="Why 'bookdownplus' {#why__bookdownplus_}"></node>
<node TEXT="Giants' Shoulders {#giants__shoulders}"></node></node>
<node TEXT="Quick Start {#quick_start}">
<node TEXT="Preparation {#preparation}"></node>
<node TEXT="Installation of 'bookdownplus' {#installation_of__bookdownplus_}"></node>
<node TEXT="How to use {#how_to_use}"></node>
<node TEXT="More output formats"></node>
<node TEXT="More templates"></node>
<node TEXT="A magic trick"></node>
<node TEXT="Recommendations"></node></node>
<node TEXT="Basic {#basic}">
<node TEXT="Markdown Syntax {#markdown_syntax}">
<node TEXT="What is Markdown {#what_is_markdown}"></node>
<node TEXT="Basic syntax {#basic_syntax}"></node>
<node TEXT="Chapters {#chapters}"></node>
<node TEXT="Figures and tables {#figures_and_tables}"></node>
<node TEXT="References {#references}"></node>
<node TEXT="Theorems, lemma, definitions, etc. {#theorems__lemma__definitions__etc_}"></node>
<node TEXT="Export Word document {#export_word_document}"></node>
<node TEXT="Equations numbering {#equations_numbering}"></node></node>
<node TEXT="R, RStudio and bookdown {#r__rstudio_and_bookdown}"></node>
<node TEXT="LaTeX and Pandoc {#latex_and_pandoc}"></node>
<node TEXT="Workflow {#workflow}"></node></node>
<node TEXT="Simple {#simple}"></node>
<node TEXT="Lifestyle {#lifestyle}">
<node TEXT="Journal {#journal}"></node>
<node TEXT="Poem book {#poem_book}"></node>
<node TEXT="Music {#music}"></node></node>
<node TEXT="Office {#office}">
<node TEXT="Mail {#mail}">
<node TEXT="Arguments for mail content"></node>
<node TEXT="Mail themes"></node></node>
<node TEXT="Calendar {#calendar}"></node></node>
<node TEXT="Academic {#academic}">
<node TEXT="Articles {#articles}"></node>
<node TEXT="Thesis {#thesis}"></node>
<node TEXT="Poster {#poster}"></node>
<node TEXT="Chemistry {#chemistry}"></node></node>
<node TEXT="Advanced {#advanced}">
<node TEXT="Chinese {#chinese}"></node>
<node TEXT="Mind Map {#mind_map}"></node>
<node TEXT="Create Your Own Templates {#customize}"></node></node>
<node TEXT="FAQ {#faq}"></node>
<node TEXT="Bibliography {-}"></node>
</node></map>
